import type {
  ActivityItem,
  AiInsight,
  AiMessage,
  AppUser,
  Company,
  Customer,
  DashboardSummary,
  FieldMapping,
  InboundLoad,
  IntegrationConnection,
  InventoryItem,
  OutboundOrder,
  ReportDefinition,
  StorageLocation,
  Warehouse,
} from "@/types";

/** Top-bar / form selector options — labeled as 3PL companies in the UI. */
export const DEMO_WAREHOUSES: Warehouse[] = [
  { id: "wh-1", code: "LOGIFORGE", name: "LogiForge Demo 3PL", timezone: "America/Chicago" },
  { id: "wh-2", code: "HARBOR", name: "Harborline Logistics", timezone: "America/Chicago" },
  { id: "wh-3", code: "SUMMIT", name: "Summit Freight Partners", timezone: "America/New_York" },
];

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: "cust-1",
    code: "ACME",
    name: "Acme Industrial",
    contactEmail: "ops@acme.example",
    contactPhone: "+1-214-555-0101",
    isActive: true,
  },
  {
    id: "cust-2",
    code: "NORD",
    name: "Nordic Polymers",
    contactEmail: "logistics@nordic.example",
    contactPhone: "+1-404-555-0144",
    isActive: true,
  },
  {
    id: "cust-3",
    code: "PAC",
    name: "Pacific Components",
    contactEmail: "ops@paccomp.example",
    isActive: false,
  },
];

export const DEMO_LOCATIONS: StorageLocation[] = [
  {
    id: "loc-1",
    warehouseId: "wh-1",
    code: "A-01-01",
    zone: "A",
    aisle: "01",
    rack: "01",
    bin: "01",
    isActive: true,
  },
  {
    id: "loc-2",
    warehouseId: "wh-1",
    code: "A-01-02",
    zone: "A",
    aisle: "01",
    rack: "01",
    bin: "02",
    isActive: true,
  },
  {
    id: "loc-3",
    warehouseId: "wh-1",
    code: "B-12-04",
    zone: "B",
    aisle: "12",
    rack: "04",
    bin: "01",
    isActive: true,
  },
  {
    id: "loc-4",
    warehouseId: "wh-2",
    code: "C-03-08",
    zone: "C",
    aisle: "03",
    rack: "08",
    bin: "02",
    isActive: true,
  },
];

export const DEMO_INBOUND: InboundLoad[] = [
  {
    id: "inb-1",
    loadNumber: "INB-2026-0841",
    warehouseId: "wh-1",
    warehouseName: "LogiForge Demo 3PL",
    customerId: "cust-1",
    customerName: "Acme Industrial",
    supplierName: "Midwest Steel Co",
    arrivalDate: "2026-08-04T08:30:00Z",
    carrier: "Swift Transport",
    trailerNumber: "TRL-44921",
    status: "Draft",
    lineCount: 4,
    totalWeight: 12840,
    lines: [
      {
        id: "inb-1-l1",
        materialCode: "STL-PLATE-12",
        materialDescription: "Steel plate 12mm",
        batchNumber: "B2026-4412",
        palletId: "PLT-100221",
        locationCode: "A-01-01",
        weight: 4800,
        quantity: 80,
        boxCount: 0,
      },
      {
        id: "inb-1-l2",
        materialCode: "BRG-HSG-90",
        materialDescription: "Bearing housing 90mm",
        batchNumber: "B2026-3301",
        palletId: "PLT-100222",
        locationCode: "B-12-04",
        weight: 3200,
        quantity: 400,
        boxCount: 40,
      },
      {
        id: "inb-1-l3",
        materialCode: "GKT-SIL-22",
        materialDescription: "Silicone gasket kit",
        batchNumber: "B2026-1199",
        palletId: "PLT-100223",
        locationCode: "A-01-02",
        weight: 1840,
        quantity: 200,
        boxCount: 40,
      },
      {
        id: "inb-1-l4",
        materialCode: "BOLT-M12",
        materialDescription: "Hex bolt M12 pack",
        batchNumber: "B2026-5520",
        palletId: "PLT-100224",
        locationCode: "A-01-01",
        weight: 3000,
        quantity: 600,
        boxCount: 60,
      },
    ],
  },
  {
    id: "inb-2",
    loadNumber: "INB-2026-0838",
    warehouseId: "wh-1",
    warehouseName: "LogiForge Demo 3PL",
    customerId: "cust-2",
    customerName: "Nordic Polymers",
    supplierName: "Helsinki Resins",
    arrivalDate: "2026-08-03T14:15:00Z",
    carrier: "XPO Logistics",
    status: "Received",
    receivedAt: "2026-08-03T16:40:00Z",
    lineCount: 6,
    totalWeight: 9200,
  },
  {
    id: "inb-3",
    loadNumber: "INB-2026-0832",
    warehouseId: "wh-2",
    warehouseName: "Harborline Logistics",
    customerId: "cust-1",
    customerName: "Acme Industrial",
    arrivalDate: "2026-08-02T11:00:00Z",
    status: "Cancelled",
    lineCount: 2,
    totalWeight: 2100,
  },
];

export const DEMO_INVENTORY: InventoryItem[] = [
  {
    id: "inv-1",
    warehouseId: "wh-1",
    warehouseName: "LogiForge Demo 3PL",
    customerId: "cust-1",
    customerName: "Acme Industrial",
    materialCode: "STL-PLATE-12",
    materialDescription: "Steel plate 12mm",
    batchNumber: "B2026-4412",
    palletId: "PLT-100221",
    locationCode: "A-01-01",
    originalWeight: 2400,
    remainingWeight: 2400,
    quantity: 40,
    boxCount: 0,
    status: "Available",
    lastUpdatedAt: "2026-08-03T16:40:00Z",
  },
  {
    id: "inv-2",
    warehouseId: "wh-1",
    warehouseName: "LogiForge Demo 3PL",
    customerId: "cust-2",
    customerName: "Nordic Polymers",
    materialCode: "RES-PELLET-A",
    materialDescription: "Polymer resin pellets Grade A",
    batchNumber: "NR-7781",
    palletId: "PLT-100318",
    locationCode: "A-01-02",
    originalWeight: 1000,
    remainingWeight: 420,
    quantity: 21,
    boxCount: 21,
    status: "Partial",
    lastUpdatedAt: "2026-08-04T09:12:00Z",
  },
  {
    id: "inv-3",
    warehouseId: "wh-1",
    warehouseName: "LogiForge Demo 3PL",
    customerId: "cust-1",
    customerName: "Acme Industrial",
    materialCode: "BRG-HSG-90",
    materialDescription: "Bearing housing 90mm",
    batchNumber: "B2026-3301",
    palletId: "PLT-100109",
    locationCode: "B-12-04",
    originalWeight: 860,
    remainingWeight: 860,
    quantity: 120,
    boxCount: 12,
    status: "Hold",
    lastUpdatedAt: "2026-08-01T11:20:00Z",
  },
  {
    id: "inv-4",
    warehouseId: "wh-2",
    warehouseName: "Harborline Logistics",
    customerId: "cust-2",
    customerName: "Nordic Polymers",
    materialCode: "FILM-ROLL-4",
    materialDescription: "Stretch film roll 4mil",
    batchNumber: "AT-2209",
    palletId: "PLT-220441",
    locationCode: "C-03-08",
    originalWeight: 640,
    remainingWeight: 640,
    quantity: 80,
    boxCount: 0,
    status: "Reserved",
    lastUpdatedAt: "2026-08-04T07:05:00Z",
  },
  {
    id: "inv-5",
    warehouseId: "wh-1",
    warehouseName: "LogiForge Demo 3PL",
    customerId: "cust-1",
    customerName: "Acme Industrial",
    materialCode: "GKT-SIL-22",
    materialDescription: "Silicone gasket kit",
    batchNumber: "B2026-1199",
    palletId: "PLT-100055",
    locationCode: "A-01-01",
    originalWeight: 180,
    remainingWeight: 95,
    quantity: 38,
    boxCount: 8,
    status: "Partial",
    lastUpdatedAt: "2026-08-04T10:01:00Z",
  },
];

export const DEMO_OUTBOUND: OutboundOrder[] = [
  {
    id: "out-1",
    orderNumber: "OUT-2026-2201",
    warehouseId: "wh-1",
    warehouseName: "LogiForge Demo 3PL",
    customerId: "cust-1",
    customerName: "Acme Industrial",
    shipDate: "2026-08-04T15:00:00Z",
    carrier: "FedEx Freight",
    destination: "Houston Plant",
    status: "Draft",
    lineCount: 3,
    totalWeight: 1860,
    totalPallets: 2,
    lines: [
      {
        id: "out-1-l1",
        inventoryItemId: "inv-1",
        materialCode: "STL-PLATE-12",
        materialDescription: "Steel plate 12mm",
        batchNumber: "B2026-4412",
        palletId: "PLT-100221",
        weight: 500,
        quantity: 8,
        boxCount: 0,
      },
      {
        id: "out-1-l2",
        inventoryItemId: "inv-5",
        materialCode: "GKT-SIL-22",
        materialDescription: "Silicone gasket kit",
        batchNumber: "B2026-1199",
        palletId: "PLT-100055",
        weight: 860,
        quantity: 20,
        boxCount: 4,
      },
      {
        id: "out-1-l3",
        inventoryItemId: "inv-2",
        materialCode: "RES-PELLET-A",
        materialDescription: "Polymer resin pellets Grade A",
        batchNumber: "NR-7781",
        palletId: "PLT-100318",
        weight: 500,
        quantity: 10,
        boxCount: 5,
      },
    ],
  },
  {
    id: "out-2",
    orderNumber: "OUT-2026-2194",
    warehouseId: "wh-1",
    warehouseName: "LogiForge Demo 3PL",
    customerId: "cust-2",
    customerName: "Nordic Polymers",
    shipDate: "2026-08-03T18:30:00Z",
    carrier: "Old Dominion",
    destination: "Charlotte DC",
    status: "Shipped",
    shippedAt: "2026-08-03T18:22:00Z",
    lineCount: 5,
    totalWeight: 4120,
    totalPallets: 4,
  },
  {
    id: "out-3",
    orderNumber: "OUT-2026-2198",
    warehouseId: "wh-2",
    warehouseName: "Harborline Logistics",
    customerId: "cust-2",
    customerName: "Nordic Polymers",
    shipDate: "2026-08-04T12:00:00Z",
    status: "Picking",
    lineCount: 2,
    totalWeight: 640,
    totalPallets: 1,
    lines: [
      {
        id: "out-3-l1",
        inventoryItemId: "inv-4",
        materialCode: "FILM-ROLL-4",
        materialDescription: "Stretch film roll 4mil",
        batchNumber: "AT-2209",
        palletId: "PLT-220441",
        weight: 640,
        quantity: 80,
        boxCount: 0,
      },
    ],
  },
];

export const DEMO_USERS: AppUser[] = [
  {
    id: "user-1",
    email: "admin@logiforge.demo",
    displayName: "Alex Rivera",
    isActive: true,
    roles: ["CompanyAdmin"],
    lastLoginAt: "2026-08-04T08:01:00Z",
  },
  {
    id: "user-2",
    email: "recv@logiforge.demo",
    displayName: "Jordan Lee",
    isActive: true,
    roles: ["ReceivingClerk"],
    lastLoginAt: "2026-08-04T07:45:00Z",
  },
  {
    id: "user-3",
    email: "ship@logiforge.demo",
    displayName: "Sam Okonkwo",
    isActive: true,
    roles: ["ShippingClerk"],
    lastLoginAt: "2026-08-03T16:20:00Z",
  },
];

export const DEMO_COMPANY: Company = {
  id: "co-1",
  name: "LogiForge Demo 3PL",
  code: "LOGIFORGE",
  legalName: "LogiForge Logistics LLC",
  status: "Active",
  primaryContactEmail: "ops@logiforge.demo",
  timezone: "America/Chicago",
};

export const DEMO_INTEGRATIONS: IntegrationConnection[] = [
  {
    id: "int-1",
    name: "Customer ERP — Acme",
    type: "Rest",
    status: "Connected",
    lastSyncAt: "2026-08-04T09:55:00Z",
    endpoint: "https://api.acme.example/wms",
  },
  {
    id: "int-2",
    name: "Carrier EDI Feed",
    type: "Webhook",
    status: "Pending",
    endpoint: "https://hooks.logiforge.demo/edi",
  },
  {
    id: "int-3",
    name: "Nightly Inventory CSV",
    type: "Csv",
    status: "Error",
    lastSyncAt: "2026-08-03T02:10:00Z",
  },
];

export const DEMO_FIELD_MAPPINGS: FieldMapping[] = [
  { id: "fm-1", sourceField: "sku", targetField: "materialCode" },
  { id: "fm-2", sourceField: "lot", targetField: "batchNumber" },
  { id: "fm-3", sourceField: "qty", targetField: "quantity", transform: "toDecimal" },
  { id: "fm-4", sourceField: "wt_lbs", targetField: "weight" },
  { id: "fm-5", sourceField: "pallet_barcode", targetField: "palletId" },
];

export const DEMO_DASHBOARD: DashboardSummary = {
  todayInbound: 6,
  todayShipments: 11,
  onHand: 1482,
  utilizationPct: 78,
  partial: 14,
  onHold: 3,
  delayed: 2,
};

export const DEMO_ACTIVITY: ActivityItem[] = [
  {
    id: "act-1",
    timestamp: "2026-08-04T10:12:00Z",
    actor: "Jordan Lee",
    action: "Received load",
    entityType: "Inbound",
    entityRef: "INB-2026-0838",
  },
  {
    id: "act-2",
    timestamp: "2026-08-04T09:48:00Z",
    actor: "Sam Okonkwo",
    action: "Confirmed shipment",
    entityType: "Outbound",
    entityRef: "OUT-2026-2194",
  },
  {
    id: "act-3",
    timestamp: "2026-08-04T09:20:00Z",
    actor: "Alex Rivera",
    action: "Placed hold",
    entityType: "Inventory",
    entityRef: "PLT-100109",
  },
  {
    id: "act-4",
    timestamp: "2026-08-04T08:55:00Z",
    actor: "System",
    action: "Sync completed",
    entityType: "Integration",
    entityRef: "Customer ERP — Acme",
  },
];

export const DEMO_AI_INSIGHTS: AiInsight[] = [
  {
    id: "ai-1",
    title: "Partial pallet risk in Zone A",
    detail: "14 partial pallets are blocking putaway lanes. Consolidate before peak outbound.",
    severity: "warning",
  },
  {
    id: "ai-2",
    title: "Inbound dock 2 underutilized",
    detail: "Dock 2 has 40% idle time this morning — shift trailer INB-2026-0841 to reduce wait.",
    severity: "info",
  },
  {
    id: "ai-3",
    title: "On-time ship rate strong",
    detail: "96% of shipments confirmed within SLA over the last 7 days.",
    severity: "success",
  },
];

export const DEMO_AI_SUGGESTIONS = [
  "Which SKUs are below reorder threshold?",
  "Show delayed outbound for LogiForge Demo 3PL",
  "Summarize inbound received today",
  "List pallets on hold with reason",
];

export const DEMO_AI_WELCOME: AiMessage = {
  id: "msg-welcome",
  role: "assistant",
  content:
    "I'm the LogiForge operations assistant. Ask about inventory, inbound queues, outbound delays, or 3PL company utilization. I can suggest next actions when you're authorized.",
  // Fixed timestamp — avoids SSR/client hydration mismatch from new Date()
  createdAt: "2026-08-04T08:00:00.000Z",
  actions: [
    { label: "Open inbound", href: "/inbound" },
    { label: "View inventory", href: "/inventory" },
  ],
};

export const DEMO_REPORTS: ReportDefinition[] = [
  {
    id: "rpt-1",
    name: "Daily Inventory Snapshot",
    category: "Inventory",
    description: "On-hand by customer, material, and slot.",
    lastRunAt: "2026-08-04T06:00:00Z",
  },
  {
    id: "rpt-2",
    name: "Inbound Receipt Log",
    category: "Inbound",
    description: "Loads received with line-level weights and batches.",
    lastRunAt: "2026-08-03T18:00:00Z",
  },
  {
    id: "rpt-3",
    name: "Outbound Performance",
    category: "Outbound",
    description: "Shipments, OTIF, and carrier mix.",
  },
  {
    id: "rpt-4",
    name: "Utilization by Zone",
    category: "Slots",
    description: "Slot occupancy and idle slots.",
    lastRunAt: "2026-08-02T06:00:00Z",
  },
];

export const ALL_PERMISSIONS = [
  "dashboard.view",
  "inbound.view",
  "inbound.create",
  "inbound.edit",
  "inbound.approve",
  "inventory.view",
  "inventory.adjust",
  "inventory.export",
  "outbound.view",
  "outbound.create",
  "outbound.edit",
  "outbound.ship",
  "reports.view",
  "reports.export",
  "customers.view",
  "customers.manage",
  "locations.view",
  "locations.manage",
  "users.view",
  "users.create",
  "users.edit",
  "company.view",
  "company.edit",
  "warehouse.view",
  "ai.use",
  "integrations.manage",
  "settings.manage",
  "admin.full",
];
