services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: logiforge
      POSTGRES_USER: logiforge
      POSTGRES_PASSWORD: logiforge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logiforge"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=logiforge;Username=logiforge;Password=logiforge
      ConnectionStrings__Redis: redis:6379
      Jwt__Key: LogiForge_Dev_Signing_Key_ChangeMe_32chars!
      Cors__Origins__0: http://localhost:3000
      Swagger__Enabled: "true"
      Cache__UseRedis: "true"
    ports:
      - "5080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.web
      args:
        NEXT_PUBLIC_API_URL: /api/v1
        NEXT_PUBLIC_ALLOW_DEMO_LOGIN: "true"
        API_ORIGIN: http://api:8080
    environment:
      API_ORIGIN: http://api:8080
      NEXT_PUBLIC_ALLOW_DEMO_LOGIN: "true"
      NEXT_PUBLIC_REQUIRE_ACCESS_REQUEST: "true"
      DEMO_REQUEST_TO: tirthsoni1810@gmail.com
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata:
